# Generated by Django 5.2.1 on 2025-05-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('development', 'Development'), ('deployment', 'Deployment'), ('devops', 'DevOps'), ('designing', 'Designing')], default='development', max_length=20),
        ),
    ]
